---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-laptop

# description will be included in the image's metadata
description: Customized Fedora COSMIC Atomic

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43-20251110

# module configuration, executed in order
modules:
  - from-file: files.yml
  - from-file: dnf.yml
  - from-file: brew.yml
  - from-file: flatpaks.yml
  - from-file: fonts.yml
  - from-file: script.yml
  - from-file: systemd.yml

  - type: signing
